# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "153.0.8010.2.0"
  chromedriver_version: ${{ (version | split("."))[0:4] | join(".") }}
  python_check_max: "3.14"

package:
  name: python-chromedriver-binary
  version: ${{ version }}

source:
  - url: https://github.com/danielkaiser/python-chromedriver-binary/archive/v${{ version }}.tar.gz
    sha256: 8bad649ad3ab4234a45d16efc72acd0612d0a3c7808475eaf77e023b807fe9b6
  - if: target_platform == "linux-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/linux64/chromedriver-linux64.zip
      sha256: 5bc3ddececefa942cbff3fd76464e341942bf427ff28455c0c4a16277b281ac1
  - if: target_platform == "osx-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/mac-x64/chromedriver-mac-x64.zip
      sha256: 8db2a385ce68a9c424424e9dd4da588c733ecad00f82047a6cd4deedbdf14846
  - if: target_platform == "osx-arm64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/mac-arm64/chromedriver-mac-arm64.zip
      sha256: d495ee414f55cc0a720bbcbd7f38de24925700e8b78917518988ba2d3acb30d8
  - if: target_platform == "win-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/win32/chromedriver-win32.zip
      sha256: e84806126d7fc0c8054e15ac5cf3615c36e93bc438673f909df862255d946e44

build:
  number: 0
  dynamic_linking:
    binary_relocation: ${{ not osx }}
  python:
    version_independent: true
    entry_points:
      - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path
  script:
    - if: not win
      then:
        - chmod +x chromedriver
      else:
        # see https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/.60pip.20install.60.20failing.20on.20Windows.20today/with/603912616
        - set PIP_USE_DEPRECATED=legacy-certs
        - set PYTHONHASHSEED=0
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: chromedriver_binary
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      file: run_test.py

about:
  homepage: https://pypi.org/project/chromedriver-binary
  repository: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_file:
    - LICENSE
    - LICENSE.chromedriver
    - THIRD_PARTY_NOTICES.chromedriver
  summary: Downloads and installs the chromedriver binary version
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - williamjamir
    - bollwyvl
