# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "152.0.7941.0.0"
  chromedriver_version: ${{ (version | split("."))[0:4] | join(".") }}
  python_check_max: "3.14"

package:
  name: python-chromedriver-binary
  version: ${{ version }}

source:
  - url: https://github.com/danielkaiser/python-chromedriver-binary/archive/v${{ version }}.tar.gz
    sha256: e1f8e2e769d16f2d3d79c22e09e915a7e35a52f978b3eecbcabc4fe3c6253237
  - if: target_platform == "linux-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/linux64/chromedriver-linux64.zip
      sha256: ec6a62bfb5494cb6a50b88b7dd55595c6a12cc46be866ca65da70ee701107518
  - if: target_platform == "osx-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/mac-x64/chromedriver-mac-x64.zip
      sha256: dc3ce907ed815d6b15cafd8e6addb1d14fd4e4243a613cd067316243c7be191b
  - if: target_platform == "osx-arm64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/mac-arm64/chromedriver-mac-arm64.zip
      sha256: 9dfeee20fb52c593b2fb1cd31735f2cef5fbd538b643d40df3fbb304f53f66c1
  - if: target_platform == "win-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/win32/chromedriver-win32.zip
      sha256: edcad1212890e1cb87635b05a93e8585cff10e1a4539d783adedd54a08f53ed7

build:
  number: 0
  dynamic_linking:
    binary_relocation: ${{ not osx }}
  python:
    version_independent: true
    entry_points:
      - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path
  script:
    - if: not win
      then:
        - chmod +x chromedriver
      else:
        # see https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/.60pip.20install.60.20failing.20on.20Windows.20today/with/603912616
        - set PIP_USE_DEPRECATED=legacy-certs
        - set PYTHONHASHSEED=0
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: chromedriver_binary
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      file: run_test.py

about:
  homepage: https://pypi.org/project/chromedriver-binary
  repository: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_file:
    - LICENSE
    - LICENSE.chromedriver
    - THIRD_PARTY_NOTICES.chromedriver
  summary: Downloads and installs the chromedriver binary version
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - williamjamir
    - bollwyvl
