# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "157.0.8081.0.0"
  chromedriver_version: ${{ (version | split("."))[0:4] | join(".") }}
  python_check_max: "3.14"

package:
  name: python-chromedriver-binary
  version: ${{ version }}

source:
  - url: https://github.com/danielkaiser/python-chromedriver-binary/archive/v${{ version }}.tar.gz
    sha256: 50fb9f5e2903484489cb3bb84eabe3b6fe19b7e087601932f6eed9204d7d2a66
  - if: target_platform == "linux-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/linux64/chromedriver-linux64.zip
      sha256: 528f6701020bc94398faddfd4704de931ee48c6b9154cb90ac82c3d16c766cae
  - if: target_platform == "osx-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/mac-x64/chromedriver-mac-x64.zip
      sha256: c89e27dc31f3d9eecae9163f5f249fa2bcce62669cb316f8f3550148bc3f5bd6
  - if: target_platform == "osx-arm64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/mac-arm64/chromedriver-mac-arm64.zip
      sha256: b5eab1d88e63592c0200ab1777cb76c3cc42df465837c72cc6a6bfcd6417dd36
  - if: target_platform == "win-64"
    then:
      url: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${{ chromedriver_version }}/win32/chromedriver-win32.zip
      sha256: aff18c3c8a5559a61c21fab4fbc69a26b15a3ac799516674b661572fa4cb6f31

build:
  number: 0
  dynamic_linking:
    binary_relocation: ${{ not osx }}
  python:
    version_independent: true
    entry_points:
      - chromedriver-path = chromedriver_binary.utils:print_chromedriver_path
  script:
    - if: not win
      then:
        - chmod +x chromedriver
      else:
        # see https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/.60pip.20install.60.20failing.20on.20Windows.20today/with/603912616
        - set PIP_USE_DEPRECATED=legacy-certs
        - set PYTHONHASHSEED=0
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: chromedriver_binary
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      file: run_test.py

about:
  homepage: https://pypi.org/project/chromedriver-binary
  repository: https://github.com/danielkaiser/python-chromedriver-binary
  license: MIT
  license_file:
    - LICENSE
    - LICENSE.chromedriver
    - THIRD_PARTY_NOTICES.chromedriver
  summary: Downloads and installs the chromedriver binary version
  description: |
    Downloads and installs the chromedriver binary for automated
    testing of webapps. The installer supports Linux, MacOS and Windows
    operating systems.

extra:
  recipe-maintainers:
    - williamjamir
    - bollwyvl
